FROM postgres:16-alpine

# Установка bash и других утилит (по желанию, можно расширить)
RUN apk add --no-cache bash

# Оставляем контейнер в интерактивном режиме, чтобы он не завершался
CMD ["postgres"] 